version: "3"
services:
  app:
    container_name: cohesion-app
    build: builds/app/bundle/
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      # - MONGO_URL=mongodb://root:aMTBrcI5GjLAVAqeNbGMZh7ChlfZ5iu@mongo:27017/cohesion
      - MONGO_URL=mongodb://mongo:27017/cohesion
      # - ROOT_URL=http://localhost:3000/
      - PORT=3000
  mongo:
    container_name: cohesion-mongo
    image: mongo:2.6
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=aMTBrcI5GjLAVAqeNbGMZh7ChlfZ5iu
